# set the directories below and copy this file as `config.yaml`
data_dir: "./data/"
paper_dir: "./paper/current/"

eca_decompositions:
  # gh: "data/eca_decompositions/gh_df.csv"
  wedge: "data/eca_decompositions/wedge_df.csv"
  imin: "data/eca_decompositions/imin_df.csv"
  pm: "data/eca_decompositions/pm_df.csv"
  ccs: "data/eca_decompositions/ccs_df.csv"
  boolean: "data/eca_decompositions/boolean_df.csv"
  # syndisc: "data/eca_decompositions/syndisc_df.csv"

eca_scripts:
  # gh: "scripts/decompositions/eca_analysis_gh.py"
  wedge: "scripts/decompositions/eca_analysis_wedge.py"
  imin: "scripts/decompositions/eca_analysis_imin.py"
  pm: "scripts/decompositions/eca_analysis_pm.py"
  ccs: "scripts/decompositions/eca_analysis_ccs.py"
  # syndisc: "scripts/decompositions/eca_analysis_syndisc.py"
